version: "2"
services:
    db:
        image: mysql:5.6
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=citynavigatorrootpass
          - MYSQL_DATABASE=citynavigator
          - MYSQL_USER=citynavigator
          - MYSQL_PASSWORD=citynavigatorpass
        volumes:
          - /var/lib/mysql

    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ../citynavigator:/var/www/app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
        links:
            - php
        networks:
            - code-network

    php:
        build: fpm/
        volumes:
            - ../citynavigator:/var/www/app
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
